### ISSUE TITLE
[Documentation]  Open a Wiki for in depth docu

### ISSUE THREAD

**Issue by lapistano** [liip/LiipDataAggregatorBundle#10]
Further make use of Nelmio/NelmioApiDocBundle to provide documentation for developers

**Comment by dbu** [comment]
+1 for having nelmio apidoc annotations

the doc would better live in Resources/doc and be compiled on readthedocs. we did that for [foshttpcache](http://foshttpcache.readthedocs.org/) - i am happy to help set it up here too.

**Comment by lapistano** [comment]
Doesn't this look nice #readthedocs
As a matter of fact I was thinking about the Resources/doc location as well today .. will keep you posted.

superseded by #11
